# inherit_from: .rubocop_todo.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7.1　
  TargetRailsVersion: 6.0.3.4　
  Exclude: 
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema*.rb"
    - "node_modules/**/*"
    - "db/migrate/**/*" 
    - "app/channels/**/*"
    - "config/**/*"
    - "config.ru"
    - "bin/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "test/**/*"
    - "Gemfile"
    - "Rakefile"
    - "helpers/**/*"
    - "db/seeds.rb"