# inherit_from: .rubocop_todo.yml

# inherit_from: .rubocop_todo.yml

inherit_from:
  - .rubocop_airbnb.yml

#ここにはrubocopでコード解析したくないファイルやフォルダを指定します
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'

# AllCops:
#   TargetRubyVersion: 2.7.1
#   TargetRailsVersion: 6.0.3.4
#   Exclude:
#     - "vendor/**/*" # rubocop config/default.yml
#     - "db/schema*.rb"
#     - "node_modules/**/*"
#     - "db/migrate/**/*"
#     - "app/channels/**/*"
#     - "config/**/*"
#     - "config.ru"
#     - "bin/**/*"
#     - "public/**/*"
#     - "tmp/**/*"
#     - "log/**/*"
#     - "test/**/*"
#     - "Gemfile"
#     - "Rakefile"
#     - "helpers/**/*"
#     - "db/seeds.rb"
#     - "spec/**/*"




 
Style/AsciiComments:
  Enabled: false


Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
  
  
Style/ClassAndModuleChildren:
  Enabled: false
  
Naming/AsciiIdentifiers:
  Enabled: false
  
Layout/LineLength:
  Enabled: false